experiment:
  dataset: voc
  target_class_name: person
  target_class_id: 14
  poisoning_ratio: 1.0
  eps: 0.062745098
  steps: [40]
  seeds: [0, 1, 2]
  num_classes: 20
  reference_target_map50: 0.81
  reference_non_target_map50: 0.78

data:
  dataset_root: /root/autodl-tmp/ue_project/VOC_0712_Kaggle_Ready
  train_images: images/train
  train_labels: labels/train
  val_images: images/val
  val_labels: labels/val
  instance_mask_dir: ""
  allow_pseudo_mask_fallback: true

platform:
  mode: cloud
  run_root: /root/autodl-tmp/ue_project/runs_formal
  resume: false
  zip_after_stage: false
  save_every_n_images: 50
  save_every_n_epochs: 10
  pack_every_n_epochs: 10
  debug: false

surrogate:
  model: yolov8n
  ckpt: /root/autodl-tmp/ue_project/checkpoints/voc20_surrogate.pt
  num_classes: 20
  imgsz: 640
  eot_samples: 4

victim:
  model: yolov8n
  init: configs/voc_yolov8n_20cls.yaml
  cache: false
  amp: true
  epochs: 200
  imgsz: 640
  batch: 12
  workers: 4
  optimizer: SGD
  cos_lr: true
  close_mosaic: 10
  save_period: 10
  device: "0"
  lr0: 0.01
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005

methods:
  em_bbox:
    support_type: bbox
    step_size: 0.007843137
    noise_scale: 1.0

  em_mask:
    support_type: mask
    step_size: 0.007843137
    noise_scale: 1.0

  rem_mask:
    support_type: mask
    step_size: 0.007843137
    noise_scale: 1.0
    eot_samples: 4

  ours_mask:
    support_type: mask
    ring_width: 4

    enable_conditional_sps: true
    enable_midfreq_search: true
    enable_jnd_gain: true
    enable_assignment_shortcut: true
    enable_shape_entanglement: true

    shortcut_frequency_mode: midfreq_sparse
    shortcut_num_bases: 2

    assignment_topk: 100
    align_alpha: 1.0
    align_beta: 6.0
    assign_margin: 0.4

    lambda_align: 4.0
    lambda_rank: 2.0
    lambda_shape: 1.0
    lambda_preserve: 1.0
    lambda_suppress: 0.5

    lambda_jnd: 0.5
    lambda_tv: 0.001
    lambda_budget: 10.0

    jnd_floor: 0.2
    jnd_ceiling: 1.0
    eot_samples: 4
    suppress_step_size: 0.003921569
