experiment:
  dataset: voc
  target_class_name: person
  target_class_id: 14
  poisoning_ratio: 1.0
  eps: 0.062745098
  steps: [40]
  seeds: [0, 1, 2]
  num_classes: 20
  method: tap_mask
  reference_target_map50: 0.81
  reference_non_target_map50: 0.78

data:
  dataset_root: /root/autodl-tmp/ue_project/VOC_0712_Kaggle_Ready
  train_images: images/train
  train_labels: labels/train
  val_images: images/val
  val_labels: labels/val
  instance_mask_dir: /root/autodl-tmp/ue_project/VOC_0712_Kaggle_Ready/taus_masks
  allow_pseudo_mask_fallback: true

platform:
  mode: cloud
  run_root: /root/autodl-tmp/ue_project/runs
  resume: false
  zip_after_stage: false
  save_every_n_images: 50
  save_every_n_epochs: 10
  pack_every_n_epochs: 10
  debug: false

surrogate:
  model: yolov8n
  ckpt: /root/autodl-tmp/ue_project/checkpoints/voc20_surrogate.pt
  num_classes: 20
  imgsz: 640
  eot_samples: 4

victim:
  model: yolov8n
  init: configs/voc_yolov8n_20cls.yaml
  cache: true
  amp: true
  epochs: 200
  imgsz: 640
  batch: 36
  workers: 16
  optimizer: SGD
  cos_lr: true
  close_mosaic: 100
  save_period: 10
  device: "0"
  lr0: 0.01
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005

methods:
  tap_mask:
    support_type: mask
    target_class_id: 14
    eps: 0.062745098
    alpha: 0.007843137
    pgd_steps: 40
    random_start: true
    objective: untargeted_det_loss
    use_target_only_labels: true
    use_prebaked_instance_mask: true
    strict_instance_mask: false
    poison_batch_size: 16
    poison_amp: false
    use_global_steps: false
